import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  late Map<String, String> _localizedStrings;

  Future<bool> load() async {
    // English strings
    final en = {
      "appTitle": "Saudagar AI",
      "tabCapture": "Capture",
      "tabDemand": "Demand",
      "tabInsights": "Insights",
      "tabAdvisor": "Advisor",
      "tapMicToRecord": "Tap Mic to Record Demand",
      "recordingVoice": "Recording voice... Tap again to send",
      "sendingToCloud": "Sending to cloud...",
      "microphonePermissionDenied": "Microphone permission denied",
      "demandIntelligence": "Demand Intelligence",
      "unavailableItems": "Top Unavailable Items",
      "customerRequests": "Top Customer Requests",
      "demandScores": "Predictive Demand Scores",
      "businessInsights": "Business Insights",
      "currentWeather": "Current Weather",
      "trendingSearch": "Trending Search",
      "upcomingFestivals": "Upcoming Festivals",
      "daysAway": "days away",
      "refreshInsights": "Refresh Insights",
      "procurementAdvisor": "Procurement Advisor",
      "generatePurchaseList": "Generate Purchase List",
      "verifyProduct": "Verify Product",
      "noneOfThese": "None of these",
      "error": "Error: ",
      "learned": "Learned!",
      "demandCaptureTerminal": "Demand Capture Terminal",
      "hinglishSimulator": "Hinglish Demo Simulator (Tap to trigger pipeline)",
      "lastExtractedEvent": "Last Extracted Event",
      "rawLabel": "Raw: ",
      "matchedLabel": "Matched: ",
      "statusLabel": "Status: ",
      "availableLabel": "Available",
      "unavailableLabel": "Unavailable (Stockout)",
      "weatherForecast": "Local Weather Forecast",
      "festivalAlert": "Festival Demand Alert",
      "monsoonSpikes": "Monsoon Search Spikes",
      "demandMetricsTitle": "Demand Intelligence Metrics",
      "scoreLabel": "Score: ",
      "procurementAdvisorTitle": "AI Procurement Agent Advisor",
      "dismiss": "Dismiss",
      "acceptOrder": "Accept & Order",
      "noDemandEvents": "No demand events analyzed yet.\nUse the simulator or mic to create demand.",
      "noInsights": "No business insights stored in Firestore yet.\nClick 'Refresh Insights' above to trigger.",
      "noRecommendations": "No procurement recommendations generated.\nAdd demand out-of-stocks to trigger Procurement reasoning.",
      "trendingProducts": "Trending Products: ",
      "noRecommendationsToShare": "No recommendations to share.",
      "listIsEmpty": "List is empty.",
      "sharePurchaseList": "Share Purchase List",
      "purchaseList": "Purchase List",
      "generatedBySaudagar": "Generated by Saudagar AI Kirana Intelligence.",
      "processingSarvam": "Processing voice on Sarvam AI...",
      "audioFailed": "Audio recording failed",
      "simulationSending": "Sending simulation to cloud...",
      "biTriggered": "Triggered Business Intelligence Agent refresh!",
      "biError": "Error triggering BI: ",
      "cityLabel": "City: ",
      "humidityLabel": "Humidity: ",
      "sourceLabel": "Source: ",
      "gearingUp": "Gearing up: ",
      "mumbai": "Mumbai",
      "instantNoodles": "Instant Noodles",
      "beverages": "Beverages",
      "monsoonDetail": "Customers searching hot drinks/foods due to wet weather.",
      "inventoryOptimal": "Inventory levels are optimal."
    };

    // Hindi strings
    final hi = {
      "appTitle": "सौदागर AI",
      "tabCapture": "माइक",
      "tabDemand": "मांग",
      "tabInsights": "अंतर्दृष्टि",
      "tabAdvisor": "सलाहकार",
      "tapMicToRecord": "मांग रिकॉर्ड करने के लिए माइक दबाएं",
      "recordingVoice": "आवाज़ रिकॉर्ड हो रही है... भेजने के लिए फिर से दबाएं",
      "sendingToCloud": "क्लाउड पर भेजा जा रहा है...",
      "microphonePermissionDenied": "माइक्रोफोन की अनुमति नहीं मिली",
      "demandIntelligence": "मांग की जानकारी",
      "unavailableItems": "अनुपलब्ध आइटम",
      "customerRequests": "शीर्ष ग्राहक मांगें",
      "demandScores": "संभावित मांग स्कोर",
      "businessInsights": "व्यापार की अंतर्दृष्टि",
      "currentWeather": "वर्तमान मौसम",
      "trendingSearch": "ट्रेंडिंग सर्च",
      "upcomingFestivals": "आने वाले त्योहार",
      "daysAway": "दिन दूर",
      "refreshInsights": "अंतर्दृष्टि ताज़ा करें",
      "procurementAdvisor": "खरीद सलाहकार",
      "generatePurchaseList": "खरीद सूची बनाएं",
      "verifyProduct": "उत्पाद सत्यापित करें",
      "noneOfThese": "इनमें से कोई नहीं",
      "error": "त्रुटि: ",
      "learned": "सीख लिया!",
      "demandCaptureTerminal": "मांग कैप्चर टर्मिनल",
      "hinglishSimulator": "हिंग्लिश डेमो सिम्युलेटर (पाइपलाइन चलाने के लिए दबाएं)",
      "lastExtractedEvent": "अंतिम निकाला गया परिणाम",
      "rawLabel": "मूल वाक्य: ",
      "matchedLabel": "संबद्ध: ",
      "statusLabel": "स्थिति: ",
      "availableLabel": "उपलब्ध",
      "unavailableLabel": "अनुपलब्ध (स्टॉक खत्म)",
      "weatherForecast": "स्थानीय मौसम का पूर्वानुमान",
      "festivalAlert": "त्योहार मांग चेतावनी",
      "monsoonSpikes": "मानसून सर्च ट्रेंड्स",
      "demandMetricsTitle": "मांग इंटेलिजेंस मेट्रिक्स",
      "scoreLabel": "स्कोर: ",
      "procurementAdvisorTitle": "AI खरीद सलाहकार",
      "dismiss": "खारिज करें",
      "acceptOrder": "स्वीकार और ऑर्डर करें",
      "noDemandEvents": "अभी तक कोई मांग दर्ज नहीं की गई है।\nमांग बनाने के लिए सिम्युलेटर या माइक का उपयोग करें।",
      "noInsights": "अभी तक कोई व्यावसायिक जानकारी उपलब्ध नहीं है।\nताज़ा करने के लिए ऊपर 'अंतर्दृष्टि ताज़ा करें' पर क्लिक करें।",
      "noRecommendations": "कोई खरीद अनुशंसा नहीं मिली।\nखरीद सुझाव प्राप्त करने के लिए मांग दर्ज करें।",
      "trendingProducts": "ट्रेंडिंग उत्पाद: ",
      "noRecommendationsToShare": "साझा करने के लिए कोई अनुशंसा नहीं है।",
      "listIsEmpty": "सूची खाली है।",
      "sharePurchaseList": "खरीद सूची साझा करें",
      "purchaseList": "खरीद सूची",
      "generatedBySaudagar": "सौदागर AI किराना इंटेलिजेंस द्वारा जनरेट किया गया।",
      "processingSarvam": "Sarvam AI पर आवाज प्रोसेस की जा रही है...",
      "audioFailed": "ऑडियो रिकॉर्डिंग विफल रही",
      "simulationSending": "सिमुलेशन क्लाउड पर भेजा जा रहा है...",
      "biTriggered": "बिजनेस इंटेलिजेंस एजेंट रिफ्रेश ट्रिगर किया गया!",
      "biError": "BI रिफ्रेश करने में त्रुटि: ",
      "cityLabel": "शहर: ",
      "humidityLabel": "आर्द्रता: ",
      "sourceLabel": "स्रोत: ",
      "gearingUp": "तैयारी: ",
      "mumbai": "मुंबई",
      "instantNoodles": "इंस्टेंट नूडल्स",
      "beverages": "पेय पदार्थ",
      "monsoonDetail": "गीले मौसम के कारण ग्राहक गर्म पेय/खाद्य पदार्थों की तलाश कर रहे हैं।",
      "inventoryOptimal": "इन्वेंट्री का स्तर बिल्कुल सही है।"
    };

    _localizedStrings = locale.languageCode == 'hi' ? hi : en;
    return true;
  }

  String translate(String key) {
    return _localizedStrings[key] ?? key;
  }
  
  String iHeardNotSure(String rawProduct) {
    if (locale.languageCode == 'hi') {
      return "मैंने सुना '\$rawProduct', लेकिन मुझे यकीन नहीं है कि यह कौन सा उत्पाद है। कृपया चुनें:";
    }
    return "I heard '\$rawProduct', but I'm not sure which product it is. Please select:";
  }
  
  String learnedAlias(String rawProduct, String canonical) {
    if (locale.languageCode == 'hi') {
      return "सीख लिया! '\$rawProduct' अब '\$canonical' है";
    }
    return "Learned! '\$rawProduct' is now '\$canonical'";
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    AppLocalizations localizations = AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
